#!/bin/sh
echo "Build"
python -m mkdocs build

echo "Move Azure Files"
cp azure/* site/

echo "Clean up container"
az storage blob delete-batch --auth-mode login --account-name adamonazure --source '$web'

echo "Uploading to container"
az storage blob upload-batch --auth-mode login --destination 'https://adamonazure.blob.core.windows.net/$web' --source site/
